data_acquisition:
    
  BATCHES: ["far1", "far2", "far3"]
  PHOTOS_PER_BATCH: 20
  CAPTURE_INTERVAL: 1.5
    
    
model:
  YOLO_MODEL_PATH: "C:\\Users\\Austin\\Face-recognition\\weights\\yolov8n-face.pt"
  YOLO_ONNX_PATH: "C:\\Users\\Austin\\Face-recognition\\weights\\yolov8n-face.onnx"
  ARC_MODEL_PATH: "C:\\Users\\Austin\\Face-recognition\\weights\\arcface_r100.onnx"
  ARCFACE_MODEL_PATH: "C:\\Users\\Austin\\Face-recognition\\weights\\w600k_r50.onnx"
  IMAGE_SIZE: 112
  CONF_THRESHOLD   : 0.5                
  PADDING          : 20


directory:
  ENROLLMENT_DIR: "C:\\Users\\Austin\\Face-recognition\\data\\enrollment"
  EMBEDDINGS_DIR: "C:\\Users\\Austin\\Face-recognition\\data\\embeddings"

hardware:
  WEBCAM_INDEX: 0
