data_acquisition:
    
  BATCHES: ["far1", "far2", "far3"]
  PHOTOS_PER_BATCH: 20
  CAPTURE_INTERVAL: 1.5
    
    
model:
  YOLO_MODEL_PATH: "/home/austin/autoattend/Face-recognition/weights/yolov8n-face.pt"
  YOLO_ONNX_PATH: "/home/austin/autoattend/Face-recognition/weights/yolov8n-face.onnx"
  ARC_MODEL_PATH: "/home/austin/autoattend/Face-recognition/weights/arcface.onnx"
  ARCFACE_MODEL_PATH: "/home/austin/autoattend/Face-recognition/weights/w600k_r50.onnx"
  IMAGE_SIZE: 112
  YOLO_CONF_THRESH : 0.40
  ARCFACE_SIM_THRESH: 0.40
  PADDING          : 20


directory:
  ENROLLMENT_DIR: "/home/austin/autoattend/Face-recognition/data/enrollment"
  EMBEDDINGS_DIR: "/home/austin/autoattend/Face-recognition/data/embeddings"

hardware:
  WEBCAM_INDEX: 0
